name: NordicByNature
favicon: null
layout_spectrum: 0.99978
typography_spectrum: 0.5364541762974113
title: Neoprene Lunch bags for the masses
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3277704908978194
  lightness: 0.75
  saturation: 0.14315155264921486
  rhythmicContrast: 0
purpose: []
